#!/bin/bash

echo "starting to setup an NPM project"

cp index.html ../index.html
cp index.mjs ../index.mjs
cp index.css ../index.css
cp template.gitignore ../.gitignore

cd ..
touch README.md
npm init

git submodule add https://github.com/jauntyjocularjay/kwikgit.git sh
git submodule add https://github.com/jauntyjocularjay/phaserhelpers.git phaserhelpers
git submodule add https://github.com/jauntyjocularjay/vanillajscomponents.git vjsc

bash sh/gitBranches

echo "enter 'npmcommands' to finish the process"

bash sh/gitDSubmodule

echo "and we are done! Happy coding!"

